"use strict";
exports.__esModule = true;
var Cliente_1 = require("./class/Cliente");
var CuentaAhorro_1 = require("./class/CuentaAhorro");
var CuentaCorriente_1 = require("./class/CuentaCorriente");
var cliente1 = new Cliente_1.Cliente("Federico", "Batalla", 34334935);
var cliente2 = new Cliente_1.Cliente("Milena", "Gonzales", 52899099);
var cuentaCorriente = new CuentaCorriente_1.CuentaCorriente(cliente1);
var cuentaAhorro = new CuentaAhorro_1.CuentaAhorro(cliente2, 2.5);
console.log("-------Prueba Cuenta Corriente-------");
console.log(cuentaCorriente.toString());
console.log("ingreso 1000");
cuentaCorriente.ingresar(1000);
console.log(cuentaCorriente.toString());
console.log("actualizo saldo");
cuentaCorriente.actualizarSaldo();
console.log(cuentaCorriente.toString());
console.log("retiro 345");
console.log(cuentaCorriente.retirar(345));
console.log(cuentaCorriente.toString());
console.log("retiro 2000");
console.log(cuentaCorriente.retirar(2000));
console.log(cuentaCorriente.toString());
console.log("-------Prueba Cuenta Ahorro-------");
console.log(cuentaAhorro.toString());
console.log("ingreso 5000");
cuentaAhorro.ingresar(5000);
console.log(cuentaAhorro.toString());
console.log("actualizo saldo interes 5%");
cuentaAhorro.actualizarSaldo(5);
console.log(cuentaAhorro.toString());
console.log("retiro 3000");
console.log(cuentaAhorro.retirar(2000));
console.log(cuentaAhorro.toString());
console.log("retiro 3250");
console.log(cuentaAhorro.retirar(3250));
console.log(cuentaAhorro.toString());
