"use strict";
exports.__esModule = true;
var Entrenador_1 = require("./class/Entrenador");
var Jugador_1 = require("./class/Jugador");
var Kinesiologo_1 = require("./class/Kinesiologo");
var Seleccion_1 = require("./class/Seleccion");
var delantero = new Jugador_1.Jugador("Enzo", "Perez", 34334935, "01/01/1989", "Delantero");
var defensor = new Jugador_1.Jugador("Matias ", "Maidana", 35162369, "04/01/1995", "Defensor");
var arquero = new Jugador_1.Jugador("Franco", "Armani", 57487229, "01/08/1988", "Arquero");
var entrenador = new Entrenador_1.Entrenador("Marcelo", "Gallardo", 15236987, "09/10/1975");
var kinesiologo = new Kinesiologo_1.Kinesiologo("Juan", "Beltran", 16789456, "15/08/1975");
var argentina = new Seleccion_1.Seleccion("Argentina", defensor, delantero, arquero, entrenador, kinesiologo);
console.log("------integrantes------");
console.log(argentina.tostring());
console.log("-----------------------");
console.log("------Conferencia------");
console.log(argentina.darConferencia(entrenador));
console.log("-----------------------");
console.log("------Partido ------");
console.log(argentina.jugar());
